# Generated by Django 6.0.6 on 2026-07-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Mixing', 'Mixing Machine'), ('Packing', 'Packing Machine'), ('Conveyor', 'Conveyor'), ('Crusher', 'Crusher'), ('Dryer', 'Dryer'), ('Other', 'Other')], default='Other', max_length=50)),
                ('image', models.ImageField(upload_to='products/')),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price_range', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=100)),
                ('height', models.CharField(blank=True, max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('power', models.CharField(blank=True, max_length=100)),
                ('voltage', models.CharField(blank=True, max_length=100)),
                ('capacity', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=150)),
                ('warranty', models.CharField(blank=True, max_length=100)),
                ('applications', models.TextField(blank=True)),
                ('features', models.TextField(blank=True)),
                ('working_principle', models.TextField(blank=True)),
                ('video_link', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
