# Generated by Django 6.0.6 on 2026-07-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_range',
        ),
    ]
