# Generated by Django 6.0.6 on 2026-07-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('machine', models.CharField(choices=[('Corrugation Machine', 'Corrugation Machine'), ('Hydraulic Press', 'Hydraulic Press'), ('Paper Cutting Machine', 'Paper Cutting Machine'), ('Box Stitching Machine', 'Box Stitching Machine'), ('Custom Machine', 'Custom Machine')], max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
