# Generated by Django 6.0.6 on 2026-07-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='category',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
